/*******************************************************************************
 * Copyright (c) 2006-2010 eBay Inc. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.08 at 02:01:56 AM PDT 
//


package org.ebayopensource.turmeric.assetcreation.artifacts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for AssetInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssetInput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="assetType" type="{http://www.ebayopensource.org/AssetCreation}AssetType"/>
 *         &lt;element name="sourceAssetID" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="libraryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="captureTemplateName" type="{http://www.ebayopensource.org/AssetCreation}CaptureTemplateName"/>
 *         &lt;element name="lifeCycleState" type="{http://www.ebayopensource.org/AssetCreation}LifeCycleState"/>
 *         &lt;element name="numberOfAssets" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="suffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="persist" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="needFullAsset" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="wsdlDocumentLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="published" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="deleteConsumedAssets" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssetInput", propOrder = {
    "id",
    "assetType",
    "sourceAssetID",
    "libraryName",
    "captureTemplateName",
    "lifeCycleState",
    "numberOfAssets",
    "prefix",
    "suffix",
    "comments",
    "persist",
    "needFullAsset",
    "wsdlDocumentLocation",
    "published",
    "deleteConsumedAssets"
})
public class AssetInput {

    /** The id. */
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String id;
    
    /** The asset type. */
    @XmlElement(required = true)
    protected AssetType assetType;
    
    /** The source asset id. */
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String sourceAssetID;
    
    /** The library name. */
    @XmlElement(required = true)
    protected String libraryName;
    
    /** The capture template name. */
    @XmlElement(required = true)
    protected CaptureTemplateName captureTemplateName;
    
    /** The life cycle state. */
    @XmlElement(required = true)
    protected LifeCycleState lifeCycleState;
    
    /** The number of assets. */
    protected int numberOfAssets;
    
    /** The prefix. */
    @XmlElement(required = true)
    protected String prefix;
    
    /** The suffix. */
    @XmlElement(required = true)
    protected String suffix;
    
    /** The comments. */
    @XmlElement(required = true)
    protected String comments;
    
    /** The persist. */
    protected boolean persist;
    
    /** The need full asset. */
    protected boolean needFullAsset;
    
    /** The wsdl document location. */
    protected String wsdlDocumentLocation;
    
    /** The published. */
    protected Boolean published;
    
    /** The delete consumed assets. */
    protected Boolean deleteConsumedAssets;

    /**
     * Gets the value of the id property.
     *
     * @return the id
     * possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the assetType property.
     *
     * @return the asset type
     * possible object is
     * {@link AssetType }
     */
    public AssetType getAssetType() {
        return assetType;
    }

    /**
     * Sets the value of the assetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetType }
     *     
     */
    public void setAssetType(AssetType value) {
        this.assetType = value;
    }

    /**
     * Gets the value of the sourceAssetID property.
     *
     * @return the source asset id
     * possible object is
     * {@link String }
     */
    public String getSourceAssetID() {
        return sourceAssetID;
    }

    /**
     * Sets the value of the sourceAssetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceAssetID(String value) {
        this.sourceAssetID = value;
    }

    /**
     * Gets the value of the libraryName property.
     *
     * @return the library name
     * possible object is
     * {@link String }
     */
    public String getLibraryName() {
        return libraryName;
    }

    /**
     * Sets the value of the libraryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibraryName(String value) {
        this.libraryName = value;
    }

    /**
     * Gets the value of the captureTemplateName property.
     *
     * @return the capture template name
     * possible object is
     * {@link CaptureTemplateName }
     */
    public CaptureTemplateName getCaptureTemplateName() {
        return captureTemplateName;
    }

    /**
     * Sets the value of the captureTemplateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaptureTemplateName }
     *     
     */
    public void setCaptureTemplateName(CaptureTemplateName value) {
        this.captureTemplateName = value;
    }

    /**
     * Gets the value of the lifeCycleState property.
     *
     * @return the life cycle state
     * possible object is
     * {@link LifeCycleState }
     */
    public LifeCycleState getLifeCycleState() {
        return lifeCycleState;
    }

    /**
     * Sets the value of the lifeCycleState property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifeCycleState }
     *     
     */
    public void setLifeCycleState(LifeCycleState value) {
        this.lifeCycleState = value;
    }

    /**
     * Gets the value of the numberOfAssets property.
     *
     * @return the number of assets
     */
    public int getNumberOfAssets() {
        return numberOfAssets;
    }

    /**
     * Sets the value of the numberOfAssets property.
     *
     * @param value the new number of assets
     */
    public void setNumberOfAssets(int value) {
        this.numberOfAssets = value;
    }

    /**
     * Gets the value of the prefix property.
     *
     * @return the prefix
     * possible object is
     * {@link String }
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the suffix property.
     *
     * @return the suffix
     * possible object is
     * {@link String }
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffix(String value) {
        this.suffix = value;
    }

    /**
     * Gets the value of the comments property.
     *
     * @return the comments
     * possible object is
     * {@link String }
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the persist property.
     *
     * @return true, if is persist
     */
    public boolean isPersist() {
        return persist;
    }

    /**
     * Sets the value of the persist property.
     *
     * @param value the new persist
     */
    public void setPersist(boolean value) {
        this.persist = value;
    }

    /**
     * Gets the value of the needFullAsset property.
     *
     * @return true, if is need full asset
     */
    public boolean isNeedFullAsset() {
        return needFullAsset;
    }

    /**
     * Sets the value of the needFullAsset property.
     *
     * @param value the new need full asset
     */
    public void setNeedFullAsset(boolean value) {
        this.needFullAsset = value;
    }

    /**
     * Gets the value of the wsdlDocumentLocation property.
     *
     * @return the wsdl document location
     * possible object is
     * {@link String }
     */
    public String getWsdlDocumentLocation() {
        return wsdlDocumentLocation;
    }

    /**
     * Sets the value of the wsdlDocumentLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsdlDocumentLocation(String value) {
        this.wsdlDocumentLocation = value;
    }

    /**
     * Gets the value of the published property.
     *
     * @return the boolean
     * possible object is
     * {@link Boolean }
     */
    public Boolean isPublished() {
        return published;
    }

    /**
     * Sets the value of the published property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPublished(Boolean value) {
        this.published = value;
    }

    /**
     * Gets the value of the deleteConsumedAssets property.
     *
     * @return the boolean
     * possible object is
     * {@link Boolean }
     */
    public Boolean isDeleteConsumedAssets() {
        return deleteConsumedAssets;
    }

    /**
     * Sets the value of the deleteConsumedAssets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeleteConsumedAssets(Boolean value) {
        this.deleteConsumedAssets = value;
    }

}
