/*******************************************************************************
 * Copyright (c) 2006-2010 eBay Inc. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.23 at 06:03:55 AM PST 
//


package org.ebayopensource.turmeric.assetcreation.artifacts;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for LifeCycleState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LifeCycleState">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="New"/>
 *     &lt;enumeration value="Proposed"/>
 *     &lt;enumeration value="InReview"/>
 *     &lt;enumeration value="Approved"/>
 *     &lt;enumeration value="Deployed"/>
 *     &lt;enumeration value="Deprecated"/>
 *     &lt;enumeration value="Retired"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum LifeCycleState {

    /** The NEW. */
    @XmlEnumValue("New")
    NEW("New"),
    
    /** The PROPOSED. */
    @XmlEnumValue("Proposed")
    PROPOSED("Proposed"),
    
    /** The I n_ review. */
    @XmlEnumValue("InReview")
    IN_REVIEW("InReview"),
    
    /** The APPROVED. */
    @XmlEnumValue("Approved")
    APPROVED("Approved"),
    
    /** The DEPLOYED. */
    @XmlEnumValue("Deployed")
    DEPLOYED("Deployed"),
    
    /** The DEPRECATED. */
    @XmlEnumValue("Deprecated")
    DEPRECATED("Deprecated"),
    
    /** The RETIRED. */
    @XmlEnumValue("Retired")
    RETIRED("Retired");
    private final String value;

    /**
     * Instantiates a new life cycle state.
     *
     * @param v the v
     */
    LifeCycleState(String v) {
        value = v;
    }

    /**
     * Value.
     *
     * @return the string
     */
    public String value() {
        return value;
    }

    /**
     * From value.
     *
     * @param v the v
     * @return the life cycle state
     */
    public static LifeCycleState fromValue(String v) {
        for (LifeCycleState c: LifeCycleState.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
