/*******************************************************************************
 * Copyright (c) 2006-2010 eBay Inc. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.23 at 06:03:55 AM PST 
//


package org.ebayopensource.turmeric.assetcreation.artifacts;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssetCreation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssetCreation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="assetDestinationLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="repositoryServiceEndPoint" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="assetInput" type="{http://org.ebayopensource.org/AssetCreation}AssetInput" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssetCreation", propOrder = {
    "assetDestinationLocation",
    "repositoryServiceEndPoint",
    "assetInput"
})
public class AssetCreation {

    @XmlElement(required = true)
    protected String assetDestinationLocation;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String repositoryServiceEndPoint;
    @XmlElement(required = true)
    protected List<AssetInput> assetInput;

    /**
     * Gets the value of the assetDestinationLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetDestinationLocation() {
        return assetDestinationLocation;
    }

    /**
     * Sets the value of the assetDestinationLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetDestinationLocation(String value) {
        this.assetDestinationLocation = value;
    }

    /**
     * Gets the value of the repositoryServiceEndPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepositoryServiceEndPoint() {
        return repositoryServiceEndPoint;
    }

    /**
     * Sets the value of the repositoryServiceEndPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepositoryServiceEndPoint(String value) {
        this.repositoryServiceEndPoint = value;
    }

    /**
     * Gets the value of the assetInput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assetInput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssetInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssetInput }
     * 
     * 
     */
    public List<AssetInput> getAssetInput() {
        if (assetInput == null) {
            assetInput = new ArrayList<AssetInput>();
        }
        return this.assetInput;
    }

}
