/*******************************************************************************
 * Copyright (c) 2006-2010 eBay Inc. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-257 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.23 at 06:03:55 AM PST 
//


package org.ebayopensource.turmeric.assetcreation.artifacts;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ebayopensource.turmeric.assetcreation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AssetCreation_QNAME = new QName("http://www.ebay.com/AssetCreation", "assetCreation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ebayopensource.turmeric.assetcreation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AssetCreation }
     * 
     */
    public AssetCreation createAssetCreation() {
        return new AssetCreation();
    }

    /**
     * Create an instance of {@link AssetInput }
     * 
     */
    public AssetInput createAssetInput() {
        return new AssetInput();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssetCreation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebay.com/AssetCreation", name = "assetCreation")
    public JAXBElement<AssetCreation> createAssetCreation(AssetCreation value) {
        return new JAXBElement<AssetCreation>(_AssetCreation_QNAME, AssetCreation.class, null, value);
    }

}
